Katia 7
Katerina-Tsu/AutomationPracticeShop pull request #7
Opened 2021-04-01 14:13 UTC by Katerina-Tsu

2021-04-02 19:58 UTC, vchesnakoutest requested changes
please make fixes

2021-04-02 19:58 UTC, vchesnakoutest commented on .idea/.gitignore
> +# Default ignored files
папки .idea и всё, что в ней не должно быть во фреймворке

2021-04-02 19:58 UTC, vchesnakoutest commented on AutomationPracticeShop.iml
> +<?xml version="1.0" encoding="UTF-8"?>
этого файла также не должно быть во фреймворке

2021-04-02 19:58 UTC, vchesnakoutest commented on pom.xml
> +        <webdrivermanager.version>4.2.2</webdrivermanager.version>
эта зависимость уже есть чуть ниже в файле

2021-04-02 19:58 UTC, vchesnakoutest commented on pom.xml
> +            <groupId>dom4j</groupId>
для чего эта зависимость ?

2021-04-02 19:58 UTC, vchesnakoutest commented on pom.xml
> -            <groupId>org.testng</groupId>
эту зависимость наверное не надо удалять, больше нигде в файле нету её

2021-04-02 19:58 UTC, vchesnakoutest commented on src/main/java/pages/YourShoppingCartSignInPage.java
> +package pages;
этот класс нужен для чего-то ?

2021-04-02 19:58 UTC, vchesnakoutest commented on src/test/java/tests/Customer.java
> +public class Customer {
этот объект наверное нигде не используется

2021-04-02 19:58 UTC, vchesnakoutest commented on target/test-classes/test_suite.xml
> +</suite>
target/test-classes/tests/BaseTest.class - этого файла тоже не должно быть во фреймворке

2021-04-02 19:58 UTC, vchesnakoutest commented on src/test/java/tests/TestListener.java
> +package tests;
этот класс надо положить в src/test/java/utils

2021-04-02 19:58 UTC, vchesnakoutest commented on src/test/java/tests/TestDataProviders.java
> +package tests;
этот класс надо положить в src/test/java/data_providers

2021-04-05 13:50 UTC, Katerina-Tsu commented on .idea/.gitignore
> +# Default ignored files
directory was deleted from framework

2021-04-05 13:51 UTC, Katerina-Tsu commented on AutomationPracticeShop.iml
> +<?xml version="1.0" encoding="UTF-8"?>
file was deleted from framework

2021-04-05 13:56 UTC, Katerina-Tsu commented on pom.xml
> +        <webdrivermanager.version>4.2.2</webdrivermanager.version>
was deleted

2021-04-05 14:11 UTC, Katerina-Tsu commented on pom.xml
> -            <groupId>org.testng</groupId>
ok, yes, fixed

2021-04-05 14:17 UTC, Katerina-Tsu commented on src/main/java/pages/YourShoppingCartSignInPage.java
> +package pages;
да, для написания следующих тестов

2021-04-05 14:18 UTC, Katerina-Tsu commented on src/test/java/tests/Customer.java
> +public class Customer {
пока что да, планирую переписать пользователя и ввод данных для него

2021-04-05 14:19 UTC, Katerina-Tsu commented on target/test-classes/test_suite.xml
> +</suite>
fixed

2021-04-05 14:21 UTC, Katerina-Tsu commented on src/test/java/tests/TestListener.java
> +package tests;
+

2021-04-05 14:21 UTC, Katerina-Tsu commented on src/test/java/tests/TestListener.java
> +package tests;
fixed

2021-04-05 14:22 UTC, Katerina-Tsu commented on src/test/java/tests/TestDataProviders.java
> +package tests;
fixed

2021-04-05 14:23 UTC, Katerina-Tsu commented on pom.xml
> +            <groupId>dom4j</groupId>
точно не припомню,.. вроде как решала какую-то ошибку

2021-04-06 10:08 UTC, vchesnakoutest approved these changes

2021-04-06 10:37 UTC, merged